// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _mpesaIntegration.Data;

#nullable disable

namespace mpesaIntegration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_mpesaIntegration.Models.MpesaC2B", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BillRefNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessShortCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MSISDN")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("OrgAccountBalance")
                        .HasColumnType("longtext");

                    b.Property<string>("ThirdPartyTransID")
                        .HasColumnType("longtext");

                    b.Property<string>("TransAmount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransactionType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("MpesaC2Bs");
                });
#pragma warning restore 612, 618
        }
    }
}
